baseURL = "https://rayfiyo.github.io/driving-license-quiz/"
languageCode = "ja-jp"
title = "運転免許 問題演習"
theme = "paper"
copyright = "Copyright (c) 2026, rayfiyo"

[[menu.main]]
weight = 1
name = "ホーム"
url = "/"

[[menu.main]]
weight = 2
name = "一覧（投稿）"
url = "/post/"

[[menu.main]]
weight = 3
name = "GitHub Repository"
url = "https://github.com/rayfiyo/driving-license-quiz"
